services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PROJECT_USER_NAME: ${PROJECT_USER_NAME:-admin}
      PROJECT_USER_PASSWORD: ${PROJECT_USER_PASSWORD:-password}
      PROJECT_USER_DATABASE_NAME: ${PROJECT_USER_DATABASE_NAME:-concerts-mate}
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.ci
