spring:
  application:
    name: 'Users-Service'
  datasource:
    url: jdbc:postgresql://localhost:5432/${PROJECT_USER_DATABASE_NAME}
    username: ${PROJECT_USER_NAME}
    password: ${PROJECT_USER_PASSWORD}
  rabbitmq:
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
  music-service:
    host: ${MUSIC_SERVICE_HOST:localhost}
    port: ${MUSIC_SERVICE_PORT:8000}
    schema: ${MUSIC_SERVICE_SCHEMA:http}
grpc:
  client:
    elastic-service:
      address: ${ELASTIC_SERVICE_HOST}:${ELASTIC_SERVICE_PORT}
      negotiation-type: plaintext
