spring:
  application:
    name: 'Users-Service'
  datasource:
    url: jdbc:postgresql://postgres:5432/${PROJECT_USER_DATABASE_NAME}
    username: ${PROJECT_USER_NAME}
    password: ${PROJECT_USER_PASSWORD}
