server:
  address: ${USER_SERVICE_ADDRESS}
  port: ${USER_SERVICE_PORT}
spring:
  application:
    name: 'User-Service'
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_USER_DATABASE_NAME}
    username: ${POSTGRES_USER_NAME}
    password: ${POSTGRES_USER_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASSWORD}
    queue: ${RABBITMQ_QUEUE}
  music-service:
    host: ${MUSIC_SERVICE_HOST}
    port: ${MUSIC_SERVICE_PORT}
    scheme: ${MUSIC_SERVICE_SCHEME}
  scheduler:
    fixed_rate: ${SCHEDULER_FIXED_RATE}
grpc:
  client:
    elastic-service:
      address: static://${ELASTIC_SERVICE_HOST}:${ELASTIC_SERVICE_PORT}
      negotiation-type: plaintext
