name: Container Health Check

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  container-health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run health checks
        run: docker-compose up -d

      - name: Run health checks
        run: |
          export $(grep -E -v '^#' .env | xargs)
          echo "Environment variables sourced from .env file."

          docker-compose up -d

          docker-compose exec -T postgres pg_isready
          export PGPASSWORD="$PROJECT_USER_PASSWORD"

          echo $PROJECT_USER_NAME
          echo $PROJECT_USER_DATABASE_NAME
          echo $PROJECT_USER_PASSWORD

          docker-compose exec -T postgres psql -U $PROJECT_USER_NAME -d $PROJECT_USER_DATABASE_NAME -c "SELECT * FROM pg_roles WHERE rolname='$PROJECT_USER_NAME';" | grep -q $PROJECT_USER_NAME || exit 1

      - name: Run health checks
        run: docker-compose down -v
