name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          debug: true
          script: |
            whoami
            cd ~/User-Service
            git reset --hard
            git pull origin main
             cat << EOF > .env
            USER_SERVICE_ADDRESS=0.0.0.0
            USER_SERVICE_PORT=${{ SECRETS.USER_SERVICE_PORT }}

            POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
            POSTGRES_USER_DATABASE_NAME=${{ secrets.POSTGRES_USER_DATABASE_NAME }}
            POSTGRES_USER_NAME=${{ secrets.POSTGRES_USER_NAME }}
            POSTGRES_USER_PASSWORD=${{ secrets.POSTGRES_USER_PASSWORD }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}

            RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }}
            RABBITMQ_PORT=${{ secrets.RABBITMQ_PORT }}
            RABBITMQ_DEFAULT_USER=${{ secrets.RABBITMQ_DEFAULT_USER }}
            RABBITMQ_DEFAULT_PASS=${{ secrets.RABBITMQ_DEFAULT_PASS  }}
            RABBITMQ_DEFAULT_PASSWORD=${{ secrets.RABBITMQ_DEFAULT_PASS  }}
            RABBITMQ_QUEUE=${{ secrets.RABBITMQ_QUEUE }}
            
            MUSIC_SERVICE_HOST=${{ secrets.HOST }}
            MUSIC_SERVICE_PORT=${{ secrets.MUSIC_SERVICE_PORT }}
            MUSIC_SERVICE_SCHEME=http

            SCHEDULER_FIXED_RATE=${{ secrets.SCHEDULER_FIXED_RATE }}

            ELASTIC_SERVICE_HOST=${{ secrets.HOST }}
            ELASTIC_SERVICE_PORT=${{ secrets.ELASTIC_SERVICE_PORT }}

            EOF
            docker compose -f deploy.yml up --build -d --force-recreate